### ISSUE TITLE
java is broken

### ISSUE THREAD

**Issue by spuder** [Appdynamics/appdynamics-cookbooks#64]
Getting the following when trying to deploy a java application

```
================================================================================
           Error executing action `put` on resource 'ark[javaagent]'
           ================================================================================

           Addressable::URI::InvalidURIError
           ---------------------------------
           Invalid port number: "\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\cache"

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/appdynamics/recipes/java_agent.rb

            23: ark 'javaagent' do
            24:   url "file://#{node['appdynamics']['java_agent']['zip']}"
            25:   path agent['install_dir']
            26:   owner agent['owner']
            27:   action :put
            28: end
            29:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/appdynamics/recipes/java_agent.rb:23:in `from_file'

           ark("javaagent") do
             action [:put]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :ark
             cookbook_name "appdynamics"
             recipe_name "java_agent"
             url "file://C:\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\cache/AppDynamicsJavaAgent.zip"
             path "c:\\program files\\appdynamics\\javaagent/javaagent"
             owner "root"
             extension "zip"
             release_file "C:\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\cache/javaagent.zip"
           end

           Platform:
           ---------
           x64-mingw32

```

kitchen.yml

```yml
  - name: java
    run_list:
    - recipe[appdynamics::default]
    - recipe[appdynamics::java_agent]
    attributes:
      appdynamics:
        java_agent:
          version: 4.1.8.9
          checksum: bcfb91da7ee74358b902e260825d427b5901c961a2179be751430e95c46225ec
          install_dir: c:\program files\appdynamics\javaagent
        controller:
          host: host.example.com
          port: 443
          ssl: tru
          user: fooobar
          accesskey: xxxxxx
        version: 4.1.8.9
```

**Comment by dkoepke** [comment]
Please try setting `#{node['appdynamics']['java_agent']['zip']}` to be `/#{Chef::Config[:file_cache_path]}/AppDynamicsJavaAgent.zip` (note the leading slash).

**Comment by spuder** [comment]
I assume you are referring to this line? 

https://github.com/Appdynamics/appdynamics-cookbooks/blob/master/recipes/java_agent.rb#L24

**Comment by dkoepke** [comment]
You can set this attribute on a node

**Comment by spuder** [comment]
I've added to my kitchen.yml

```
    attributes:
      appdynamics:
        packages_site: https://packages.netdocuments.com:443/artifactory/nd-appdynamics
        java_agent:
          version: 4.1.8.9
          checksum: bcfb91da7ee74358b902e260825d427b5901c961a2179be751430e95c46225ec
          install_dir: c:\appdynamics
          zip: /#{Chef::Config[:file_cache_path]}/AppDynamicsJavaAgent.zip
```

getting

```
           ================================================================================
           Error executing action `create` on resource 'remote_file[/#{Chef::Config[:file_cache_path]}/AppDynamicsJavaAgent.zip]'
           ================================================================================

           Chef::Exceptions::EnclosingDirectoryDoesNotExist
           ------------------------------------------------
           Parent directory /#{Chef::Config[:file_cache_path]} does not exist.

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/appdynamics/recipes/java_agent.rb

            16: remote_file node['appdynamics']['java_agent']['zip'] do
            17:   source package_source
            18:   checksum agent['checksum']
            19:   backup false
            20:   mode '0444'
            21: end
            22:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/appdynamics/recipes/java_agent.rb:16:in `from_file'
```

I tried changing my berksfile to point to a local copy and modified line 24 directly

```
ark 'javaagent' do
  url "file://#{Chef::Config[:file_cache_path]}/AppDynamicsJavaAgent.zip"
  path agent['install_dir']
  owner agent['owner']
  action :put
end
```

Getting similar error

```
         * ark[javaagent] action put[2016-12-21T21:38:17+00:00] WARN: file://C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/AppDynamicsJavaAgent.zip was an invalid URI. Trying to escape invalid characters


           ================================================================================
           Error executing action `put` on resource 'ark[javaagent]'
           ================================================================================

           Addressable::URI::InvalidURIError
           ---------------------------------
           Invalid port number: "\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\cache"

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/appdynamics/recipes/java_agent.rb

            23: ark 'javaagent' do
            24:   url "file://#{Chef::Config[:file_cache_path]}/AppDynamicsJavaAgent.zip"
            25:   path agent['install_dir']
            26:   owner agent['owner']
            27:   action :put
            28: end
            29:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/appdynamics/recipes/java_agent.rb:23:in `from_file'

           ark("javaagent") do
             action [:put]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :ark
             cookbook_name "appdynamics"
             recipe_name "java_agent"
             url "file://C:\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\cache/AppDynamicsJavaAgent.zip"
             path "c:\\appdynamics/javaagent"
             owner "root"
             extension "zip"
             release_file "C:\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\cache/javaagent.zip"
           end

           Platform:
           ---------
           x64-mingw32

```
